from .auth_routes import auth_routes
from .user_routes import user_routes
from .restaurant_routes import restaurant_routes
from .favorites_routes import favorite_routes
from .menu_item_routes import menu_item_routes
from .menu_item_img_routes import menu_item_img_routes
from .shopping_cart_routes import shopping_cart_routes
from .order_routes import order_routes
from .order_item_routes import order_item_routes
from .review_routes import review_routes
from .review_img_routes import review_img_routes
from .payment_routes import payment_routes
from .shipping_routes import shipping_routes
from .maps_routes import maps_routes
from .ubereats_routes import ubereats_routes
from .s3_routes import s3_routes
